[wokwi]
version = 1
elf = ".pio/build/esp32/firmware.elf"
firmware = ".pio/build/esp32/firmware.bin"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
#[[net.forward]]
#from = "localhost:1883"
#to = "target:1883"

[net]
gateway="ws://localhost:9011"